version: 0.2
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release
      - cd bin/Release/netcoreapp1.0/publish
      - zip ../../../../MyProject.zip *
      - cd ../../../..
      - aws cloudformation package --template-file template.yaml --s3-bucket demo3366 --output-template-file output-template.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - output-template.yaml
