AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: RequestLogging_Handler::RequestLogging_Handler.Functions:Post
      Runtime: dotnetcore2.1
      CodeUri: bin/Release/netcoreapp1.0/publish
      
